import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "./lib/utils";
import Navbar from "../components/Navbar";
import Providers from "../components/Providers";
import { Toaster } from "@/components/ui/toaster";
import "react-loading-skeleton/dist/skeleton.css";
import 'simplebar-react/dist/simplebar.min.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const light = false;

  return (
    <html lang="en" className={`${light ? "light" : "dark"}`}>
      <Providers>
        <body
          className={cn(
            `min-h-screen font-sans antialiase ${
              light ? "grainy" : "bg-background"
            }`,
            inter.className
          )}
        >
          <Toaster />
          <Navbar />
          {children}
        </body>
      </Providers>
    </html>
  );
}
